# Generated by Django 5.0.6 on 2025-08-07 13:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0002_task_assignee"),
    ]

    operations = [
        migrations.RenameField(
            model_name="task",
            old_name="assignee",
            new_name="responsible",
        ),
    ]
