# Generated by Django 5.0.6 on 2025-08-08 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0003_rename_assignee_task_responsible"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="priority",
            field=models.CharField(
                choices=[
                    ("low", "Низкий"),
                    ("medium", "Средний"),
                    ("high", "Высокий"),
                    ("critical", "Критичный"),
                ],
                default="medium",
                max_length=10,
            ),
        ),
    ]
