# Generated by Django 5.0.6 on 2025-08-20 13:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0006_taskimage"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="UserProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "display_name",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Отображаемое имя"
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("admin", "Администратор"),
                            ("manager", "Менеджер"),
                            ("editor", "Редактор"),
                            ("viewer", "Наблюдатель"),
                            ("staff", "Сотрудник"),
                            ("user", "Пользователь"),
                        ],
                        default="user",
                        max_length=32,
                        verbose_name="Роль",
                    ),
                ),
            ],
        ),
        migrations.AlterModelOptions(
            name="taskimage",
            options={"ordering": ["position"]},
        ),
        migrations.AlterField(
            model_name="taskimage",
            name="image",
            field=models.ImageField(upload_to="tasks/"),
        ),
        migrations.AlterField(
            model_name="taskimage",
            name="position",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddConstraint(
            model_name="taskimage",
            constraint=models.UniqueConstraint(
                fields=("task", "position"), name="unique_task_position"
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="profile",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
