# Generated by Django 5.0.6 on 2025-08-20 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0007_userprofile_alter_taskimage_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprofile",
            name="display_name",
            field=models.CharField(
                blank=True, default="", max_length=255, verbose_name="Отображаемое имя"
            ),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="role",
            field=models.CharField(
                blank=True, default="", max_length=64, verbose_name="Роль"
            ),
        ),
    ]
