# Generated by Django 5.0.6 on 2025-08-25 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0010_alter_project_options_project_due_date_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="completed_at",
            field=models.DateField(blank=True, null=True),
        ),
    ]
